name: Release

on:
  push:
    tags: [ 'v*' ]

# Add permissions at the workflow level
permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            suffix: linux
            ext: ""
            archive: tar.gz
            archive_cmd: tar -czf dist/evemu-utills-linux.tar.gz bin/
          - os: windows-latest
            suffix: windows
            ext: ".exe"
            archive: zip
            archive_cmd: Compress-Archive -Path bin/* -DestinationPath dist/evemu-utills-windows.zip
          - os: macos-latest
            suffix: darwin
            ext: ""
            archive: tar.gz
            archive_cmd: tar -czf dist/evemu-utills-darwin.tar.gz bin/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build merge_events
      run: |
        go build -o bin/merge-events${{ matrix.ext }} ./cmd/evemu-merge
        
    - name: Build repeat_events
      run: |
        go build -o bin/repeat-events${{ matrix.ext }} ./cmd/evemu-repeat

    - name: Compress binaries
      run: |
        mkdir -p dist
        ${{ matrix.archive_cmd }}

    - name: Upload compressed binaries
      uses: actions/upload-artifact@v4
      with:
        name: evemu-utills-${{ matrix.suffix }}
        path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Compress binaries
        run: |
          ls -la dist/evemu-utills-linux
          ls -la dist/evemu-utills-windows
          ls -la dist/evemu-utills-darwin

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Upload Release Asset - Linux
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/evemu-utills-linux/evemu-utills-linux.tar.gz
          asset_name: evemu-utills-linux.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Release Asset - Windows
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/evemu-utills-windows/evemu-utills-windows.zip
          asset_name: evemu-utills-windows.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset - MacOS
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/evemu-utills-darwin/evemu-utills-darwin.tar.gz
          asset_name: evemu-utills-darwin.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}