name: Release

on:
  push:
    tags: [ 'v*' ]

# Add permissions at the workflow level
permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            suffix: linux
            ext: ""
            archive: tar.gz
            archive_cmd: tar -czf
          - os: windows-latest
            suffix: windows
            ext: ".exe"
            archive: zip
            archive_cmd: zip -r
          - os: macos-latest
            suffix: darwin
            ext: ""
            archive: tar.gz
            archive_cmd: tar -czf

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build merge_events
      run: |
        go build -o bin/merge_events_${{ matrix.suffix }}${{ matrix.ext }} ./cmd/merge
        
    - name: Build repeat_events
      run: |
        go build -o bin/repeat_events_${{ matrix.suffix }}${{ matrix.ext }} ./cmd/repeat

    - name: Compress binaries
      run: |
        mkdir -p release
        if [ "${{ matrix.os }}" != "windows" ]; then
          ${{ matrix.archive_cmd }} release/binaries-${{ matrix.suffix }}.${{ matrix.archive }} bin/
        fi
        
    - name: Upload compressed binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.suffix }}
        path: release/binaries-${{ matrix.suffix }}.${{ matrix.archive }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: release

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}