name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            suffix: linux
            ext: ""
          - os: windows-latest
            suffix: windows
            ext: ".exe"
          - os: macos-latest
            suffix: darwin
            ext: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build merge_events
      run: |
        go build -o bin/merge_events_${{ matrix.suffix }}${{ matrix.ext }} ./cmd/merge
        
    - name: Build repeat_events
      run: |
        go build -o bin/repeat_events_${{ matrix.suffix }}${{ matrix.ext }} ./cmd/repeat
                
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.suffix }}
        path: bin/
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      run: |
        for artifact in artifacts/binaries-*/*; do
          gh release upload ${{ github.ref_name }} "$artifact" --repo ${{ github.repository }}
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}